# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 12 3 0
format B 9 3 0
label A0 = "mm"
label B0 = "deg"
leftstring A1 = "FL"
let A1 = 10
let B1 = @rtd(@atan(A1/A$5))
leftstring A2 = "FR"
let A2 = 15
let B2 = @rtd(@atan(A2/A$5))
leftstring A3 = "RL"
let A3 = 20
let B3 = @rtd(@atan(A3/A$5))
leftstring A4 = "RR"
let A4 = 25
let B4 = @rtd(@atan(A4/A$5))
leftstring A5 = "Z"
let A5 = 1000
label A7 = "deg"
label B7 = "deg_min"
label C7 = "deg_max"
leftstring A8 = "cambF"
let A8 = 17/60
let B8 = A8-30/60
let C8 = A8+30/60
leftstring A9 = "cambR"
let A9 = (-1)-4/60
let B9 = A9-45/60
let C9 = A9+45/60
goto A6
