# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Toe"
movetosheet "Toe"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 12 3 0
format B 11 3 0
format C 11 3 0
format D 13 3 0
label A0 = "mm"
label B0 = "set,mm"
label C0 = "deg"
leftstring A1 = "D"
let A1 = 150
leftstring B1 = "B"
let B1 = @rtd(@atan((A4-A4-A3+A2)/A4))
leftstring C1 = "left"
let C1 = @rtd(@atan(@dtr((A7-A8)/2/A13)))
leftstring A2 = "E"
let A2 = 1670
leftstring B2 = "G"
let B2 = @rtd(@atan((A4-A4-A4+A1)/A4))
leftstring C2 = "right"
let C2 = @rtd(@atan(@dtr((A10-A9)/2/A13)))
leftstring A3 = "B"
let A3 = 100
leftstring B3 = "A"
let B3 = @rtd(@atan((A4-A4)/A4)-@atan((A4-A4)/A4))/2
leftstring A4 = "G"
let A4 = 1620
leftstring B4 = "C"
let B4 = @rtd(@atan((A2-A1-A4+A4)/A4)-@atan((A4-A3-A4+A4)/A4))/2
leftstring A5 = "V"
let A5 = 2000
leftstring B5 = "F"
label A6 = "deg"
leftstring B6 = "H"
leftstring A7 = "A"
let A7 = 20
leftstring A8 = "C"
let A8 = -20
leftstring A9 = "F"
let A9 = -20
leftstring A10 = "H"
let A10 = 20
label B11 = "min_deg"
label C11 = "max_deg"
leftstring A12 = "caster"
let A12 = 6+43/60
let B12 = A12-1
let C12 = A12+1
leftstring A13 = "toe"
let A13 = 10
leftstring A15 = "-A-B-C-D-------------E-F-G-H-"
leftstring A16 = "   |   |      |      |   |"
leftstring A17 = "   |   |   _  V  _   |   |"
leftstring A18 = "   |   |  | | | | |  |   |"
leftstring A19 = "   +---|--| |---| |--|---+"
leftstring A20 = "       |  |_|   |_|  |"
leftstring A21 = "       |             |"
leftstring A22 = "       |             |"
leftstring A23 = "       |             |"
leftstring A24 = "       |             |"
leftstring A25 = "       |  _       _  |"
leftstring A26 = "       | | |     | | |"
leftstring A27 = "       +-| |     | |-+"
leftstring A28 = "         |_|     |_|"
goto C3
