# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 12 3 0
format B 11 3 0
format C 12 3 0
label A0 = "mm"
label B0 = "set,mm"
label C0 = "deg"
leftstring A1 = "A"
let A1 = 100
leftstring B1 = "B"
let B1 = @rtd(@atan((A4-A4-A3+A2)/A4))
leftstring C1 = "left"
let C1 = @rtd(@atan(@dtr((A10-A10)/2/A13)))
leftstring A2 = "B"
let A2 = 150
leftstring B2 = "G"
let B2 = @rtd(@atan((A4-A4-A4+A1)/A4))
leftstring C2 = "right"
let C2 = @rtd(@atan(@dtr((A10-A10)/2/A13)))
leftstring A3 = "C"
let A3 = 1815
leftstring B3 = "A"
let B3 = @rtd(@atan((A4-A4)/A4)-@atan((A4-A4)/A4))/2
leftstring A4 = "D"
let A4 = 1900
leftstring B4 = "C"
let B4 = @rtd(@atan((A2-A1-A4+A4)/A4)-@atan((A4-A3-A4+A4)/A4))/2
leftstring C4 = "bd"
let C4 = @rtd(@atan((A3-A1)/A5))
leftstring A5 = "E"
let A5 = 100
leftstring B5 = "F"
leftstring C5 = "eg"
let C5 = @rtd(@atan((A2-A4)/A5))
leftstring A6 = "F"
let A6 = 150
leftstring A7 = "G"
let A7 = 1831
leftstring A8 = "H"
leftstring A9 = "U"
let A9 = 5000
leftstring A10 = "V"
let A10 = 2000
label A11 = "deg"
label B11 = "min_deg"
label C11 = "max_deg"
leftstring A12 = "caster"
let A12 = 6+43/60
let B12 = A12-1
let C12 = A12+1
leftstring A13 = "toe"
let A13 = 10
leftstring A15 = "---A--B-------------C--D-"
leftstring A16 = "|  |  |      |      |  |"
leftstring A17 = "|  |  |   _  V  _   |  |"
leftstring A18 = "|  |  |  | | | | |  |  |"
leftstring A19 = "|  |--|--| |---| |--|--|"
leftstring A20 = "|  |  |  |_|   |_|  |  |"
leftstring A21 = "|  |  |             |  |"
leftstring A22 = "U  |  |             |  |"
leftstring A23 = "|  |  |             |  |"
leftstring A24 = "|  |  |             |  |"
leftstring A25 = "|  |  |  _       _  |  |"
leftstring A26 = "|  |  | | |     | | |  |"
leftstring A27 = "|  |  |-| |     | |-|  |"
leftstring A28 = "|  |  | |_|     |_| |  |"
leftstring A29 = "---E--F-------------G--H-"
goto A1
