# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Toe"
movetosheet "Toe"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 10 3 0
format B 12 3 0
format C 12 3 0
label A0 = "mm"
label B0 = "deg"
label C0 = "mm"
leftstring A1 = "A"
let A1 = 50
leftstring B1 = "ftoe"
let B1 = @rtd(@atan((A7-A6-A3+A2)/A9))
leftstring A2 = "B"
let A2 = 150
leftstring B2 = "rtoe"
let B2 = @rtd(@atan((A8-A5-A4+A1)/A9))
leftstring C2 = "setB"
let C2 = A1+@tan(@dtr(A16))*A2
leftstring A3 = "C"
let A3 = 1642
leftstring A4 = "D"
let A4 = 1550
leftstring B4 = "rtoe"
let B4 = @rtd(@atan((A3-A4)/A4))
leftstring C4 = "setD"
let C4 = A3-@tan(@dtr(A17))*A4
leftstring A5 = "E"
let A5 = 60
leftstring B5 = "ef"
let B5 = @rtd(@atan((A6-A5)/A14))
leftstring C5 = "d_efgh"
let C5 = @tan(@dtr(A16+B6)/2)*A14
leftstring A6 = "F"
let A6 = 167
leftstring B6 = "d_fax"
let B6 = B5+B7-B2
leftstring C6 = "setF"
let C6 = A5+C5
leftstring A7 = "G"
let A7 = 1667
leftstring B7 = "gh"
let B7 = @rtd(@atan((A8-A7)/A14))
leftstring A8 = "H"
let A8 = 1581
leftstring B8 = "steer"
let B8 = (B5-B7)/2
leftstring C8 = "setH"
let C8 = A7+C5
leftstring A9 = "U"
let A9 = 3000
leftstring A10 = "I"
let A10 = 80
leftstring B10 = "ij"
let B10 = @rtd(@atan((A10-A11)/A14))
leftstring C10 = "d_ijkl"
let C10 = @tan(@dtr(A17+B11)/2)*A14
leftstring A11 = "J"
let A11 = 80
leftstring B11 = "d_rax"
let B11 = B10+B12-B4
leftstring C11 = "setJ"
let C11 = A10-C10
leftstring A12 = "K"
let A12 = 80
leftstring B12 = "kl"
let B12 = @rtd(@atan((A12-A13)/A14))
leftstring A13 = "L"
let A13 = 80
leftstring B13 = "thrust"
let B13 = (B10-B12)/2
leftstring C13 = "setL"
let C13 = A12-C10
leftstring A14 = "W"
let A14 = 2700
label A15 = "deg"
label B15 = "min_deg"
label C15 = "max_deg"
leftstring A16 = "ftoe"
let A16 = 0
let B16 = -@rtd(@atan(2/(205*0.55*2+16*25.4)))
let C16 = -B16
leftstring A17 = "rtoe"
let A17 = @rtd(@atan(2/(205*0.55*2+16*25.4)))
let B17 = @rtd(@atan(1/(205*0.55*2+16*25.4)))
let C17 = @rtd(@atan(4/(205*0.55*2+16*25.4)))
leftstring A19 = "---A-B-----------------C-D-"
leftstring A20 = "|  | |     _     _     | |"
leftstring A21 = "|  |_|__M_| |   | |_N__|_|"
leftstring A22 = "|  | |--I-| |   | |-J--| |---"
leftstring A23 = "|  | |    |_|   |_|    | |  |"
leftstring A24 = "|  | |                 | |  |"
leftstring A25 = "U  | |                 | |  |"
leftstring A26 = "|  | |                 | |  W"
leftstring A27 = "|  | |                 | |  |"
leftstring A28 = "|  | |    _       _    | |  |"
leftstring A29 = "|  | |   | |     | |   | |  |"
leftstring A30 = "|  |-+-K-| |     | |-L-+-|---"
leftstring A31 = "|  | |   |_|     |_|   | |"
leftstring A32 = "---E-F-----------------G-H-"
leftstring A34 = "d_fax,d_rax - angular difference between front and rear axle lengths"
leftstring A35 = "In real scenario they should be equal"
goto A22
