# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Toe"
movetosheet "Toe"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 10 3 0
format B 13 3 0
format C 13 3 0
format D 13 3 0
label A0 = "mm"
label B0 = "deg"
label C0 = "mm"
label D0 = "check"
leftstring A1 = "A"
let A1 = 50
leftstring B1 = "ftoe"
let B1 = @rtd(@atan((A7-A6-A3+A2)/A9))
leftstring C1 = "setK"
let C1 = A13-@tan(@dtr(A18/2-B7))*A15
leftstring D1 = "ftoe"
let D1 = @rtd(@atan((C8-C7-C10+C9)/A9))
leftstring A2 = "B"
let A2 = 150
leftstring B2 = "rtoe"
let B2 = @rtd(@atan((A8-A5-A4+A1)/A9))
leftstring C2 = "setL"
let C2 = A14-@tan(@dtr(A18/2-B8))*A15
leftstring D2 = "rtoe"
let D2 = @rtd(@atan((C6-C5-C4+C3)/A9))
leftstring A3 = "C"
let A3 = 1642
leftstring B3 = "thrust"
let B3 = @rtd(@atan((A11-A13)/A15)-@atan((A12-A14)/A15))/2
leftstring C3 = "setA"
let C3 = A1+@tan(@dtr(A18/2-B7))*(A15+A10)
leftstring D3 = "thrust"
let D3 = @rtd(@atan((A11-C1)/A15)-@atan((A12-C2)/A15))/2
leftstring A4 = "D"
let A4 = 1550
leftstring B4 = "steer"
let B4 = @rtd(@atan((A2-A1-A6+A5)/A9)-@atan((A4-A3-A8+A7)/A9))/2
leftstring C4 = "setD"
let C4 = A4-@tan(@dtr(A18/2-B8))*(A15+A10)
leftstring D4 = "steer"
let D4 = @rtd(@atan((C9-C3-C7+C5)/A9)-@atan((C4-C10-C6+C8)/A9))/2
leftstring A5 = "E"
let A5 = 60
leftstring B5 = "ftoeL"
let B5 = B1/2+B4
leftstring C5 = "chkE"
let C5 = A5-@tan(@dtr(A18/2-B7))*(A9-A15-A10)
leftstring A6 = "F"
let A6 = 167
leftstring B6 = "ftoeR"
let B6 = B1/2-B4
leftstring C6 = "chkH"
let C6 = A8+@tan(@dtr(A18/2-B8))*(A9-A15-A10)
leftstring A7 = "G"
let A7 = 1667
leftstring B7 = "rtoeL"
let B7 = B2/2+B3
leftstring C7 = "setF"
let C7 = A6-@tan(@dtr(A17/2-B5))*(A9-A10)
leftstring A8 = "H"
let A8 = 1581
leftstring B8 = "rtoeR"
let B8 = B2/2-B3
leftstring C8 = "setG"
let C8 = A7+@tan(@dtr(A17/2-B6))*(A9-A10)
leftstring A9 = "U"
let A9 = 4000
leftstring C9 = "chkB"
let C9 = A2+@tan(@dtr(A17/2-B5))*A10
leftstring A10 = "V"
let A10 = 500
leftstring C10 = "chkC"
let C10 = A3-@tan(@dtr(A17/2-B6))*A10
leftstring A11 = "I"
let A11 = 80
leftstring A12 = "J"
let A12 = 80
leftstring A13 = "K"
let A13 = 70
leftstring A14 = "L"
let A14 = 60
leftstring A15 = "W"
let A15 = 2700
label A16 = "deg"
label B16 = "min_deg"
label C16 = "max_deg"
leftstring A17 = "ftoe"
let A17 = 0
let B17 = -@rtd(@atan(2/(205*0.55*2+16*25.4)))
let C17 = -B17
leftstring A18 = "rtoe"
let A18 = @rtd(@atan(2/(205*0.55*2+16*25.4)))
let B18 = @rtd(@atan(1/(205*0.55*2+16*25.4)))
let C18 = @rtd(@atan(4/(205*0.55*2+16*25.4)))
leftstring A20 = "---A-B-----------------C-D---"
leftstring A21 = "|  | |                 | |  |"
leftstring A22 = "|  | |     _     _     | |  V"
leftstring A23 = "|  |_|__K_| |   | |_L__|_|  |"
leftstring A24 = "|  | |----| |   | |----| |---"
leftstring A25 = "|  | |    |_|   |_|    | |  |"
leftstring A26 = "|  | |                 | |  |"
leftstring A27 = "U  | |                 | |  |"
leftstring A28 = "|  | |                 | |  W"
leftstring A29 = "|  | |                 | |  |"
leftstring A30 = "|  | |    _       _    | |  |"
leftstring A31 = "|  | |   | |     | |   | |  |"
leftstring A32 = "|  |-+-I-| |     | |-J-+-|---"
leftstring A33 = "|  | |   |_|     |_|   | |"
leftstring A34 = "---E-F-----------------G-H-"
goto C9
