# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 10 3 0
format B 12 3 0
format C 11 3 0
format D 10 3 0
leftstring A1 = "A"
let A1 = 20
leftstring B1 = "ab"
let B1 = @atan((A1-A2)/A9)/@pi*180
leftstring A2 = "B"
let A2 = 10
leftstring B2 = "cd"
let B2 = @atan((A3-A4)/A9)/@pi*180
leftstring C2 = "setB"
let C2 = A1-@tan(A11/2*@pi/180)*A9
leftstring A3 = "C"
let A3 = 20
leftstring B3 = "ef"
let B3 = @atan((A6-A5)/A9)/@pi*180
leftstring A4 = "D"
let A4 = 15
leftstring B4 = "gh"
let B4 = @atan((A8-A7)/A9)/@pi*180
leftstring C4 = "setD"
let C4 = A3-@tan(A11/2*@pi/180)*A9
leftstring A5 = "E"
let A5 = 20
leftstring B5 = "ftoe"
let B5 = B1+B2
leftstring A6 = "F"
let A6 = 24
leftstring B6 = "rtoe"
let B6 = B3+B4
leftstring C6 = "setF"
let C6 = A5+@tan(A12/2*@pi/180)*A9
leftstring A7 = "G"
let A7 = 20
leftstring B7 = "thrust"
let B7 = (B3-B4)/2
leftstring A8 = "H"
let A8 = 24
leftstring C8 = "setH"
let C8 = A7+@tan(A12/2*@pi/180)*A9
leftstring A9 = "W"
let A9 = 2700
leftstring A11 = "ftoe"
let A11 = 0
let B11 = -(@atan(2/(205*0.55*2+16*25.4))/@pi*180)
let C11 = -B11
leftstring A12 = "rtoe"
let A12 = @atan(2/(205*0.55*2+16*25.4))/@pi*180
let B12 = @atan(1/(205*0.55*2+16*25.4))/@pi*180
let C12 = @atan(4/(205*0.55*2+16*25.4))/@pi*180
goto A14
