# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 10 3 0
format B 12 3 0
format C 13 3 0
label A0 = "mm"
label B0 = "deg"
label C0 = "mm"
leftstring A1 = "A"
let A1 = 1492
leftstring A2 = "B"
let A2 = 1500
leftstring B2 = "ftoe"
let B2 = @atan((A2-A1)/A3)/@pi*180
leftstring C2 = "setB"
let C2 = A1+@tan(A17*@pi/180)*A3
leftstring A3 = "U"
let A3 = 3000
leftstring A4 = "C"
let A4 = 1521
leftstring A5 = "D"
let A5 = 1495
leftstring B5 = "rtoe"
let B5 = @atan((A4-A5)/A6)/@pi*180
leftstring C5 = "setD"
let C5 = A4-@tan(A18*@pi/180)*A6
leftstring A6 = "V"
let A6 = 3000
leftstring A7 = "E"
let A7 = 80
leftstring B7 = "ef"
let B7 = @atan((A8-A7)/A15)/@pi*180
leftstring A8 = "F"
let A8 = 82
leftstring B8 = "faxdif"
let B8 = B7+B9-B2
leftstring C8 = "setF"
let C8 = @tan((A17+B8)*@pi/180)*A15/2+A7
leftstring A9 = "G"
let A9 = 80
leftstring B9 = "gh"
let B9 = @atan((A10-A9)/A15)/@pi*180
leftstring A10 = "H"
let A10 = 84
leftstring B10 = "fturn"
let B10 = (B7-B9)/2
leftstring C10 = "setH"
let C10 = @tan((A17+B8)*@pi/180)*A15/2+A9
leftstring A11 = "I"
let A11 = 80
leftstring B11 = "ij"
let B11 = @atan((A11-A12)/A15)/@pi*180
leftstring A12 = "J"
let A12 = 75
leftstring C12 = "setJ"
leftstring A13 = "K"
let A13 = 80
leftstring B13 = "kl"
let B13 = @atan((A13-A14)/A15)/@pi*180
leftstring A14 = "L"
let A14 = 78
leftstring B14 = "thrust"
let B14 = (B11-B13)/2
leftstring C14 = "setL"
leftstring A15 = "W"
let A15 = 2700
label A16 = "deg"
label B16 = "min_deg"
label C16 = "max_deg"
leftstring A17 = "ftoe"
let A17 = 0
let B17 = -(@atan(2/(205*0.55*2+16*25.4))/@pi*180)
let C17 = -B17
leftstring A18 = "rtoe"
let A18 = @atan(2/(205*0.55*2+16*25.4))/@pi*180
let B18 = @atan(1/(205*0.55*2+16*25.4))/@pi*180
let C18 = @atan(4/(205*0.55*2+16*25.4))/@pi*180
leftstring A20 = "---|-----------D-----------|"
leftstring A21 = "|  | |---------A---------| |"
leftstring A22 = "|  | |     _   |   _     | |"
leftstring A23 = "|  | |--E-| |  |  | |-G--|_|___"
leftstring A24 = "|  |-+-J--| |  |  | |--L-+-|  |"
leftstring A25 = "|  | |    |_|  |  |_|    | |  |"
leftstring A26 = "|  | |         |         | |  |"
leftstring A27 = "|  | |         U         | |  |"
leftstring A28 = "V  | |         |         | |  W"
leftstring A29 = "|  | |         |         | |  |"
leftstring A30 = "|  | |         |         | |  |"
leftstring A31 = "|  | |---------B---------| |  |"
leftstring A32 = "|  | |    _         _    | |  |"
leftstring A33 = "|  | |-F-| |       | |-H-|_|___"
leftstring A34 = "|  |--I--| |       | |--K--|"
leftstring A35 = "|  |     |_|       |_|     |"
leftstring A36 = "---|-----------C-----------|"
goto C0
