# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format A 10 3 0
format B 12 3 0
format C 13 3 0
leftstring A1 = "A"
let A1 = 1492
leftstring A2 = "B"
let A2 = 1500
leftstring C2 = "setB"
let C2 = A1+@tan(A17*@pi/180)*A3
leftstring A3 = "U"
let A3 = 3000
leftstring B3 = "ftoe"
let B3 = @atan((A2-A1)/A3)/@pi*180
leftstring A4 = "C"
let A4 = 1495
leftstring A5 = "D"
let A5 = 1521
leftstring C5 = "setD"
let C5 = A4-@tan(A17/2*@pi/180)*A11
leftstring A6 = "V"
let A6 = 3000
leftstring B6 = "rtoe"
let B6 = @atan((A4-A5)/A6)/@pi*180
leftstring A7 = "E"
let A7 = 20
leftstring B7 = "ftoe"
let B7 = B1+B2
leftstring A8 = "F"
let A8 = 24
leftstring B8 = "rtoe"
let B8 = B4+B5
leftstring C8 = "setF"
let C8 = A7+@tan(A18/2*@pi/180)*A11
leftstring A9 = "G"
let A9 = 20
leftstring B9 = "thrust"
let B9 = (B4-B5)/2
leftstring A10 = "H"
let A10 = 24
leftstring C10 = "setH"
let C10 = A9+@tan(A18/2*@pi/180)*A11
leftstring A11 = "I"
leftstring A12 = "J"
leftstring A13 = "K"
leftstring A14 = "L"
leftstring A15 = "W"
let A15 = 2700
leftstring A17 = "ftoe"
let A17 = 0
let B17 = -(@atan(2/(205*0.55*2+16*25.4))/@pi*180)
let C17 = -B17
leftstring A18 = "rtoe"
let A18 = @atan(2/(205*0.55*2+16*25.4))/@pi*180
let B18 = @atan(1/(205*0.55*2+16*25.4))/@pi*180
let C18 = @atan(4/(205*0.55*2+16*25.4))/@pi*180
leftstring A21 = "---|-----------D-----------|"
leftstring A22 = "|  | |---------A---------| |"
leftstring A23 = "|  | |     _   |   _     | |"
leftstring A24 = "|  | |--E-| |  |  | |-G--|_|___"
leftstring A25 = "|  |-+-J--| |  |  | |--L-+-|  |"
leftstring A26 = "|  | |    |_|  |  |_|    | |  |"
leftstring A27 = "|  | |         |         | |  |"
leftstring A28 = "|  | |         U         | |  |"
leftstring A29 = "V  | |         |         | |  W"
leftstring A30 = "|  | |         |         | |  |"
leftstring A31 = "|  | |         |         | |  |"
leftstring A32 = "|  | |---------B---------| |  |"
leftstring A33 = "|  | |    _         _    | |  |"
leftstring A34 = "|  | |-F-| |       | |-H-|_|___"
leftstring A35 = "|  |--I--| |       | |--K--|"
leftstring A36 = "|  |     |_|       |_|     |"
leftstring A37 = "---|-----------C-----------|"
goto A4
